# GitHub Sponsors & Donation Options
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-supporter-button-in-your-repository

# Uncomment and add your usernames/links as needed:

# GitHub Sponsors
# github: FirmlyAware

# Other platforms (choose what works for you):
# patreon: your_username
# ko_fi: your_username
# buy_me_a_coffee: your_username
# paypal: your_paypal_email_or_link

# Custom donation link
# custom: ['https://your-donation-link.com']
